package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/blueice-mc/blueice/internal/mojang"
	"github.com/blueice-mc/blueice/internal/version"
)

type BlockState struct {
	Default    bool              `json:"default"`
	ID         int32             `json:"id"`
	Properties map[string]string `json:"properties"`
}

type Block struct {
	States []BlockState `json:"states"`
}

func hexString(v int32) string {
	return fmt.Sprintf("%02x", v)
}

func GeneratePacketTOML(tomlPath string, jsonPath string) {
	type JsonPacketStructure struct {
		ProtocolId int32 `json:"protocol_id"`
	}

	type JsonStateStructure struct {
		Clientbound map[string]JsonPacketStructure `json:"clientbound"`
		Serverbound map[string]JsonPacketStructure `json:"serverbound"`
	}

	jsonContent, err := os.ReadFile(jsonPath)
	if err != nil {
		log.Fatal(err)
	}

	var states map[string]JsonStateStructure
	if err := json.Unmarshal(jsonContent, &states); err != nil {
		log.Fatal(err)
	}

	writer, err := os.Create(tomlPath)
	if err != nil {
		log.Fatal(err)
	}
	defer writer.Close()

	_, err = writer.WriteString(`# This file is automatically generated by the BlueIce generation tool.
# Do not modify it manually unless you ABSOLUTELY know what you are doing.
`)

	if err != nil {
		log.Fatal(err)
	}

	for state, structure := range states {
		if _, err := writer.WriteString("\n[" + state + "]\n"); err != nil {
			log.Fatal(err)
		}

		if _, err := writer.WriteString("\n[" + state + ".clientbound]\n"); err != nil {
			log.Fatal(err)
		}

		for name, packet := range structure.Clientbound {
			if _, err := writer.WriteString("\"" + strings.TrimPrefix(name, "minecraft:") + "\" = 0x" + hexString(packet.ProtocolId) + "\n"); err != nil {
				log.Fatal(err)
			}
		}

		if _, err := writer.WriteString("\n[" + state + ".serverbound]\n"); err != nil {
			log.Fatal(err)
		}

		for name, packet := range structure.Serverbound {
			if _, err := writer.WriteString("\"" + strings.TrimPrefix(name, "minecraft:") + "\" = 0x" + hexString(packet.ProtocolId) + "\n"); err != nil {
				log.Fatal(err)
			}
		}
	}
}

func main() {
	log.Println("Starting generation")

	// look for the executable
	ex, _ := os.Executable()
	path := filepath.Dir(ex)

	log.Printf("Generating in %v\n", path)

	// download the server JAR using the integrated tool
	if err := mojang.DownloadServerJAR(version.GameVersion, filepath.Join(path, "server.jar")); err != nil {
		log.Fatal("Could not download server JAR: ", err)
	}

	// run the integrated data generator from mojang
	// the machine needs to have Java installed for this to work
	cmd := exec.Command("java", "-DbundlerMainClass=net.minecraft.data.Main", "-jar", filepath.Join(path, "server.jar"), "--reports", "--output", filepath.Join(path, "generated"))
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		log.Fatal("Could not generate reports directory: ", err)
	}

	GeneratePacketTOML(filepath.Join(path, "protocol.toml"), filepath.Join(path, "generated/reports/packets.json"))

	log.Println("Generation finished")

	if err := os.Remove(filepath.Join(path, "server.jar")); err != nil {
		log.Fatal("Could not remove server JAR: ", err)
	}

	if err := os.Remove(filepath.Join(path, "generated")); err != nil {
		log.Fatal("Could not remove generated reports directory: ", err)
	}
}
