package main

import (
	"BlueIce/internal/mojang"
	"BlueIce/internal/version"
	"encoding/json"
	"log"
	"maps"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
)

type BlockState struct {
	Default    bool              `json:"default"`
	ID         int32             `json:"id"`
	Properties map[string]string `json:"properties"`
}

type Block struct {
	States []BlockState `json:"states"`
}

func writeBlockMap(path string, blockMap map[string]Block) error {
	file, err := os.Create(path)
	if err != nil {
		return err
	}
	defer file.Close()

	content := `// This file is automatically generated.
package block

var DefaultBlockStates = map[string]int32{
`

	for id, block := range blockMap {
		for _, state := range block.States {
			if state.Default {
				content += "\t\"" + id + "\": " + strconv.Itoa(int(state.ID)) + ",\n"
			}
		}
	}

	content += `}

var BlockStates = map[string]int32{
`

	for id, block := range blockMap {
		for _, state := range block.States {
			properties := "["

			keys := make([]string, 0, len(state.Properties))
			for k := range maps.Keys(state.Properties) {
				keys = append(keys, k)
			}

			sort.Strings(keys)

			for _, key := range keys {
				properties += key + "=" + state.Properties[key] + ","
			}

			if properties == "[" {
				properties = ""
			} else {
				properties = properties[:len(properties)-1]
				properties += "]"
			}

			content += "\t\"" + id + properties + "\": " + strconv.Itoa(int(state.ID)) + ",\n"
		}
	}

	content += "}"

	if _, err := file.WriteString(content); err != nil {
		return err
	}

	return nil
}
func createMap(path string) (map[string]Block, error) {
	blockMap := make(map[string]Block)
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	err = json.Unmarshal(data, &blockMap)
	return blockMap, err
}

func main() {
	log.Println("Starting generation")

	ex, _ := os.Executable()
	path := filepath.Dir(ex)

	if err := mojang.DownloadServerJAR(version.GameVersion, filepath.Join(path, "server.jar")); err != nil {
		log.Fatal("Could not download server JAR: ", err)
	}

	cmd := exec.Command("java", "-DbundlerMainClass=net.minecraft.data.Main", "-jar", filepath.Join(path, "server.jar"), "--reports", "--output", "build/generated")
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		log.Fatal("Could not generate reports directory: ", err)
	}

	blockMap, err := createMap(filepath.Join(path, "generated/reports/blocks.json"))
	if err != nil {
		log.Fatal("Could not create block map: ", err)
	}

	writeBlockMap(filepath.Join(path, "states_generated.go"), blockMap)

	if err := os.Remove(filepath.Join(path, "server.jar")); err != nil {
		log.Fatal("Could not remove server JAR: ", err)
	}
}
